apiVersion: v1
kind: ConfigMap
metadata:
  name: desktop-assistant-config
data:
  MOUNT_POINT: /mnt/c/Users/lowIQ/Downloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-assistant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktop-assistant
  template:
    metadata:
      labels:
        app: desktop-assistant
    spec:
      containers:
        - name: desktop-assistant
          image: localhost/desktop-assistant-image:34
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: desktop-assistant-config
          volumeMounts:
            - name: host-volume
              mountPath: /mnt/c/Users/lowIQ/Downloads
      volumes:
        - name: host-volume
          persistentVolumeClaim:
            claimName: host-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: desktop-assistant-service
spec:
  selector:
    app: desktop-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
